name: AI Security Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, develop]

jobs:
  security-analysis:
    runs-on: ubuntu-latest
    name: 'Secure PR Guard Analysis'
    
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Secure PR Guard
        uses: siwenwang0803/secure-pr-guard@v1
        id: security-analysis
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          cost_limit: '1.00'
          analysis_depth: 'standard'
      
      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const cost = '${{ steps.security-analysis.outputs.analysis_cost }}';
            const issues = '${{ steps.security-analysis.outputs.security_issues_found }}';
            const score = '${{ steps.security-analysis.outputs.owasp_compliance_score }}';
            const summary = '${{ steps.security-analysis.outputs.analysis_summary }}';
            
            const body = `## 🛡️ Secure PR Guard Analysis
            
            | Metric | Value |
            |--------|-------|
            | 💰 **Cost** | $${cost} USD |
            | 🛡️ **Security Issues** | ${issues} found |
            | 📋 **OWASP Score** | ${score}% |
            
            **Summary:** ${summary}
            
            ---
            *Powered by [Secure PR Guard](https://github.com/siwenwang0803/secure-pr-guard)*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });