# Production overrides for docker-compose.yml
services:
  secure-pr-guard:
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=WARNING
      - PYTHONOPTIMIZE=1
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  monitoring-dashboard:
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=WARNING
    restart: always

  redis:
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.1'

  prometheus:
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'

  grafana:
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-pr-guard-admin}
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false

  nginx:
    restart: always
