# Codecov configuration for GitHub Actions
coverage:
  status:
    project:
      default:
        target: 80%
    patch:
      default:
        target: 70%
        
ignore:
  - "tests/"
  - "docs/"
  - "*.md"
