name: 'Secure PR Guard Analysis'

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, develop]

jobs:
  security-analysis:
    runs-on: ubuntu-latest
    name: 'AI Security Code Review'
    
    permissions:
      contents: read
      pull-requests: write
      issues: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Secure PR Guard
        uses: siwenwang0803/secure-pr-guard@v1
        id: security-analysis
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cost_limit: '1.00'
          analysis_depth: 'standard'
          enable_budget_guard: 'true'
          enable_owasp_scanning: 'true'
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          exclude_files: '*.md,*.txt,*.json,package-lock.json,yarn.lock'
      
      - name: Display Results
        run: |
          echo "Analysis Cost: ${{ steps.security-analysis.outputs.analysis_cost }}"
          echo "Security Issues: ${{ steps.security-analysis.outputs.security_issues_found }}"
          echo "OWASP Score: ${{ steps.security-analysis.outputs.owasp_compliance_score }}%"
          echo "Summary: ${{ steps.security-analysis.outputs.analysis_summary }}"
      
      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const cost = '${{ steps.security-analysis.outputs.analysis_cost }}';
            const issues = '${{ steps.security-analysis.outputs.security_issues_found }}';
            const score = '${{ steps.security-analysis.outputs.owasp_compliance_score }}';
            const summary = '${{ steps.security-analysis.outputs.analysis_summary }}';
            
            const body = `## 🛡️ Secure PR Guard Analysis Results
            
            | Metric | Value |
            |--------|-------|
            | 💰 **Analysis Cost** | $${cost} USD |
            | 🛡️ **Security Issues** | ${issues} found |
            | 📋 **OWASP LLM Score** | ${score}% compliant |
            
            **Summary:** ${summary}
            
            ${issues > 0 ? '⚠️ **Action Required:** Security issues detected. Please review and address the findings above.' : '✅ **All Clear:** No security issues detected in this PR.'}
            
            ---
            *Powered by [Secure PR Guard](https://github.com/siwenwang0803/secure-pr-guard) - AI Code Review with OWASP LLM Compliance*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
      
      - name: Fail on Security Issues
        if: steps.security-analysis.outputs.security_issues_found > 0
        run: |
          echo "❌ Security issues detected. Failing the workflow."
          echo "Found ${{ steps.security-analysis.outputs.security_issues_found }} security issues"
          exit 1

  # Optional: Advanced workflow with conditional analysis
  advanced-analysis:
    runs-on: ubuntu-latest
    name: 'Comprehensive Security Analysis'
    if: contains(github.event.pull_request.labels.*.name, 'security-review')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Comprehensive Analysis
        uses: siwenwang0803/secure-pr-guard@v1
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cost_limit: '5.00'
          analysis_depth: 'comprehensive'
          enable_budget_guard: 'true'
          enable_owasp_scanning: 'true'
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}