name: Test Secure PR Guard Action

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test Action
        uses: ./
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          cost_limit: '0.10'
          analysis_depth: 'basic'
